# Generated by Django 2.2.7 on 2019-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsensor',
            name='last_temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
