# Generated by Django 2.2.7 on 2019-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_monitor', '0002_tempsensor_last_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsensor',
            name='hw_id',
            field=models.CharField(default='Not_Defined', max_length=256),
        ),
    ]
